cluster:
  "profiles/slurm/submit -J {cluster.job-name} -t {cluster.time} -p {cluster.partition} -A {cluster.account} -n {cluster.ntasks} -c {cluster.cpus-per-task} -m {cluster.mem} -o {cluster.output} -g {cluster.gres} -d '{dependencies}'"
cluster-status:
  "status"
jobscript:
  "jobscript"
latency-wait:
  5
restart-times:
  1
max-jobs-per-second:
  5
max-status-checks-per-second:
  5
local-cores:
  64
jobs:
  9999
use-singularity:
  false
use-conda:
  true
keep-going:
  true
cluster-config:
 - "cluster-configs/default.yaml"
 - "cluster-configs/dug.yaml"
