cluster:
  "profiles/slurm/submit -J {cluster.job-name} -t {cluster.time} -p {cluster.partition} -A {cluster.account} -n {cluster.ntasks} -c {cluster.cpus-per-task} -m {cluster.mem} -o {cluster.output} -g {cluster.gres} -r {cluster.reservation} -d '{dependencies}'"
cluster-status:
  "status"
jobscript:
  "jobscript"
latency-wait:
  30
restart-times:
  0
max-jobs-per-second:
  2
max-status-checks-per-second:
  2
local-cores:
  4
jobs:
  512
use-singularity:
  false
use-conda:
  true
conda-frontend:
  "mamba"
keep-going:
  true
cluster-config:
 - "profiles/cluster-config.yaml"
 - "profiles/zeus/zeus.yaml"
