cluster:
  "profiles/slurm/submit -J {cluster.job-name} -t {cluster.time} -p {cluster.partition} -A {cluster.account} -n {cluster.ntasks} -c {cluster.cpus-per-task} -m {cluster.mem} -o {cluster.output} -g {cluster.gres} -d '{dependencies}'"
cluster-status:
  "status"
jobscript:
  "jobscript"
restart-times:
  1
max-jobs-per-second:
  1
max-status-checks-per-second:
  1
local-cores:
  4
jobs:
  100
use-singularity:
  false
use-conda:
  true
cluster-config:
 - "cluster-configs/default.yaml"
# - "cluster-configs/custom_cluster.yaml"
